# networks:
#   my_network:
#     driver: bridge

services:
  api:
    build: .
    command: "dev"
    network_mode: "host"

    # networks:
    #   - my_network
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # networks:
      # - my_network
  
